ARG SDK_VERSION_TAG
ARG DOCKER_REPOSITORY=mcr.microsoft.com/dotnet/sdk
FROM ${DOCKER_REPOSITORY}:${SDK_VERSION_TAG}

ARG OPENJDK_PACKAGE=openjdk-11-jre

LABEL maintainer="estafette.io" \
      description="The estafette-extension-dotnet component is an Estafette extension to build and publish .NET Core applications and libraries."

RUN grep security /etc/apt/sources.list | tee /etc/apt/security.sources.list && \
    apt-get update && \
    apt-get upgrade -y -o Dir::Etc::SourceList=/etc/apt/security.sources.list && \
    apt-get install -yq \
        $OPENJDK_PACKAGE && \
    java -version && \
    dotnet tool install --global --version 5.4.0 dotnet-sonarscanner && \
    sed -i 's/System\.Drawing\.Common\/4\.7\.0/System\.Drawing\.Common\/4\.7\.2/g' /usr/share/dotnet/sdk/7.0.202/Sdks/Microsoft.NET.ILLink.Tasks/tools/net7.0/ILLink.Tasks.deps.json && \
    sed -i 's/"System\.Drawing\.Common": "4\.7\.0"/"System\.Drawing\.Common": "4\.7\.2"/g' /usr/share/dotnet/sdk/7.0.202/Sdks/Microsoft.NET.ILLink.Tasks/tools/net7.0/ILLink.Tasks.deps.json

ENV PATH="$PATH:/root/.dotnet/tools" \
    ESTAFETTE_LOG_FORMAT="console"

COPY estafette-extension-dotnet /

ENTRYPOINT ["/estafette-extension-dotnet"]
