ARG SDK_VERSION_TAG
ARG DOCKER_REPOSITORY=mcr.microsoft.com/dotnet/core/sdk
FROM ${DOCKER_REPOSITORY}:${SDK_VERSION_TAG}

ARG OPENJDK_PACKAGE=openjdk-8-jre

LABEL maintainer="estafette.io" \
      description="The estafette-extension-dotnet component is an Estafette extension to build and publish .NET Core applications and libraries."

RUN grep security /etc/apt/sources.list | tee /etc/apt/security.sources.list && \
    apt-get update && \
    apt-get upgrade -y -o Dir::Etc::SourceList=/etc/apt/security.sources.list && \
    apt-get upgrade -y \
      libidn11 \
      libperl5.24 \
      perl \
      perl-base \
      perl-modules-5.24 && \
    apt-get install -yq \
        $OPENJDK_PACKAGE \
    && java -version \
    && dotnet tool install --global --version 4.10.0 dotnet-sonarscanner

ENV PATH="$PATH:/root/.dotnet/tools" \
    ESTAFETTE_LOG_FORMAT="console"

COPY estafette-extension-dotnet /

ENTRYPOINT ["/estafette-extension-dotnet"]